[project]
name = "tutorial-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "notebook>=7.4.5",
    "numpy>=2.3.2",
    "pandas>=2.3.1",
]
